CREATE TABLE [dbo].[PRODUCT](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](15) NULL
 CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[CATEGORY](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](15) NULL
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[CATEGORY_PRODUCT](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Category_Id] [int] NOT NULL,
	[Product_Id] [int] NOT NULL,
 CONSTRAINT [PK_CATEGORY_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CATEGORY_PRODUCT] WITH CHECK ADD
 CONSTRAINT FK_CATEGORY_PRODUCT_Category FOREIGN KEY (Category_Id) REFERENCES [dbo].[CATEGORY] (Id)

 ALTER TABLE [dbo].[CATEGORY_PRODUCT] WITH CHECK ADD
 CONSTRAINT FK_CATEGORY_PRODUCT_Product FOREIGN KEY (Product_Id) REFERENCES [dbo].[PRODUCT] (Id)


INSERT INTO  [dbo].[PRODUCT] (Name) VALUES ('Product1'), ('Product2'), ('Product3')
INSERT INTO  [dbo].[CATEGORY] (Name) VALUES ('Category1'), ('Category2'), ('Category3')

INSERT INTO  [dbo].[CATEGORY_PRODUCT] (Category_Id,Product_Id) VALUES (1,1), (2,2), (2,1)

 SELECT 
  p.Name,
  c.Name
FROM [dbo].[PRODUCT] As p
LEFT JOIN [dbo].[CATEGORY_PRODUCT] AS cp ON cp.Product_Id = p.Id
LEFT JOIN [dbo].[CATEGORY] AS c ON cp.Category_Id  = c.Id